# TMA4320 - Øving 4, LU-faktorisering med pivotering

I denne øvingen skal du lage og teste et Python-program for å gjøre LU-faktorisering med pivotering.
I store simuleringer kan det være fornuftig å bruke så lite minne som mulig, og dessuten unngå unødvendige operasjoner som krever tid. Med utgangspunkt i dette ønsker vi å lage en funksjon som tar matrisen $A$ som input og returnerer en representasjon av matriser $P$, $L$ og $U$   
$$
    PA = LU
$$
der $P$ er en permutasjonsmatrise, $L$ er en nedretriangulær matrise med 1'ere på diagonalen, og $U$ er en øvre-triangular matrise. Med *representasjon av matriser* tenker vi oss følgende: Permutasjonsmatrisen $P$ er representert av en vektor $\mathtt{P}$ slik at rad $k$ i matrisen $P$ er enhetsvektor $e_{\mathtt{P}_k}$. Vi illustrerer med et eksempel

$$
\mathtt{P}=
\left[
\begin{array}{r} 3 \\ 1 \\ 2 \end{array}
\right]\quad\Rightarrow\quad
P=\left[
\begin{array}{ccc}
0 & 0 & 1 \\ 1 & 0 & 0 \\ 0 & 1 & 0
\end{array}
\right]
$$

Vi antar at Python-funksjonen tar et todimensjonalt array $\mathtt{A}$ som input og returnerer
en *overskrevet* $\mathtt{A}$ som inneholder $L$ og $U$ i følgende forstand ved retur:
$$
\begin{array}{ll}
\mathtt{A}[\mathtt{P}[i],j] = L_{ij} & \text{for}\ i<j \\
\mathtt{A}[\mathtt{P}[i],j] = U_{ij} & \text{for}\ i\geq j
\end{array}
$$
At $L$ har 1 på diagonalen er alltid tilfelle så diagonalen til $L$ trenger ikke å lagres. De øvrige elementene i $L$ og $U$ er null og trenger selvsagt heller ikke å lagres. Med referanse til forelesningene, så kan algoritmen for LU-faktoriseringen formuleres som følger

- Input: $A$ av størrelse $n\times n$
- Initialisering
    * La $P_i = i,\ i=0,\ldots,n-1$ være en vektor (array) med $n$ komponenter
- for $k$ **in** range(n-1):
    1. Finn indeks $P_\ell$ slik at $|\mathtt{A}_{P_\ell,k}|=\max_{k\leq i \leq n-1} |\mathtt{A}_{P_i,k}|$, dvs skann kolonne $k$ fra diagonalen og ned etter største element i absoluttverdi. 
    2. Bytt om $P_k$ med $P_\ell$.
    3. Finn multiplikatorer $A_{P_i,k}\leftarrow \frac{A_{P_i,k}}{A_{P_k,k}},\ i=k+1,\ldots,n-1$.
    4. Utfør eliminasjon, dvs $A_{P_i,j}\leftarrow A_{P_i,j}-A_{P_i,k}\cdot A_{P_k,j},\ i,j=k+1,\ldots,n-1$
- Output: A,P

**Kommentar:** I praksis fins selvsagt ferdige rutiner både i Python-biblioteker og andre steder for å løse ligningsystemer på en supereffektiv måte. I praksis er det også ofte slik at mange elementer i koeffisientmatrisen $A$ er null og det kan utnyttes på ulike vis. Løseren du lager her er ganske generell. Uansett om programvaren du lager her er hyllevare så er det en god erfaring å én gang ha skrevet et slikt program selv, slik at du forstår hvordan det fungerer, hvilke feil som kan oppstå osv, og det blir enklere å skjønne blant annet feilanalyse.

**Oppgave 1** Skriv funksjon for LU-faktorisering med radvis pivotering, den kan ha header


    def mylu(A):
   
    
og returnere pivotvektoren (permutasjonsvektoren) P, og en overskrevet versjon av A. Du kan også velge å kopiere A over i en annen matrise LU i begynnelsen av funksjonen ved 

    LU = A.copy()

og skrive i og returnere denne slik at du tar vare på inputmatrisen A.

Følg algoritmen beskrevet ovenfor. Se hint om indeksering og nyttige numpy-funksjoner du kan bruke nedenfor.

**Oppgave 2** Kombiner din funksjon (mylu) med funksjonene for forover- og bakover substitusjon angitt nedenfor til å lage løsninger av lineære systemer $Ax=b$. Test ut med å bruke $A$ og $b$ fra funksjonen getAb() nedenfor.

**Kontrollspørsmål 1:** Angi permutasjonsvektoren P fra denne numeriske testen (flervalg)

**Kontrollspørsmål 2:** Angi første komponent av mellomresultatet $c$ (der $Lc=Pb$) (flervalg)

**Kontrollspørsmål 3:** Angi siste komponent i svaret $x$ (der $Ax=b$) med det kjørte eksemplet

**Godkjenningskrav**
En Jupyter notebook fil med kode som utfører Oppgave 1 og 2 skal lastes opp i Bb og det skal svares på kontrollspørsmål.



In [175]:
#Oppgave 1: 
import numpy as np
import scipy.linalg as la

def mylu(A):
    ''' Returns: 
    Vector P interpreted as a Pivot matrix (represents a matrix with unit vectors e_Pk f'in row k).
    LU is a copy of A, where the diagonal and above is U and below the diagonal is L. 
    '''
    LU = A.astype(float) #Copies A and casts all values in A to float! (Important!)
    n = A.shape[0]
    P = np.arange(n)
    for k in range(n-1):
        #print(LU)
        pivot = np.argmax(abs(A[P[k:], k]))+k
        P[pivot], P[k] = P[k], P[pivot]
        mults = LU[P[k+1:],k] / LU[P[k],k]
        LU[P[k+1:], k+1:] = LU[P[k+1:], k+1:] - np.outer(mults, LU[P[k],k+1:])
        LU[P[k+1:], k] = mults
    return LU, P

A = np.array([[1,1,-2], 
             [1,3,-1], 
             [1,5,1]])
LU, P = mylu(A)
print(LU)
print(P)

print("It becomes apparaent that mylu() is correct when comparing to the result from scipy's solution")
P, L, U = la.lu(A)
print(P)
print(L)
print(U)

[[ 1.   1.  -2. ]
 [ 1.   0.5 -0.5]
 [ 1.   4.   3. ]]
[0 2 1]
It becomes apparaent that mylu() is correct when comparing to the result from scipy's solution
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
[[1.  0.  0. ]
 [1.  1.  0. ]
 [1.  0.5 1. ]]
[[ 1.   1.  -2. ]
 [ 0.   4.   3. ]
 [ 0.   0.  -0.5]]


## Noen Python og numpy greier
I LU-faktorisering med partiell (radvis) pivotering trenger man å gjøre bruk av indirekte aksessering av arrays via en permutasjonsvektor P. Nedenfor vises noen enkle eksempler på ting man kan gjøre.

In [133]:
import numpy as np

A=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
P=np.array([2,3,0,1])
m,n = A.shape
print('A=\n',A)
print('\n\nPermutasjonsvektor P=',P)
k=1

print('\n\nRadene i A sortert i henhold til P\n skrives: A[P,]\n\n', A[P,])

print('\n\nKolonne k(=',k,') sortert i henhold til P, skrives: A[P,k]\n',A[P,k])
print('\n\n Hent siste del av kolonne k i A sortert i henhold til P: A[P[k:],k]\n', A[P[k:],k])



print('\n\n***\n\n')

print('numpy-funksjonen np.outer kan være nyttig i utregning av punkt 4 ovenfor\n')
print('Eksempel:\n La x,y være\n') 
x=np.array([1,2,3]) 
y=np.array([1,0,-1])
print('x=',x,'\ny=',y)
print('\nDa blir np.outer(x,y)=\n',np.outer(x,y))

k=2
print('\n\nNumpyfunksjonen argmax kan være nyttig når man søker pivot-element (rad som skal byttes)\n')
pivot = np.argmax(abs(A[P[k:], k]))+k
print('Skriv for eksempel: pivot = np.argmax(abs(A[P[k:], k])+k\n som gir pivot=',pivot, 'når k=',k)

AA=np.random.rand(5,5)
print('\n\n AA=\n',AA)



A=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Permutasjonsvektor P= [2 3 0 1]


Radene i A sortert i henhold til P
 skrives: A[P,]

 [[ 9 10 11 12]
 [13 14 15 16]
 [ 1  2  3  4]
 [ 5  6  7  8]]


Kolonne k(= 1 ) sortert i henhold til P, skrives: A[P,k]
 [10 14  2  6]


 Hent siste del av kolonne k i A sortert i henhold til P: A[P[k:],k]
 [14  2  6]


***


numpy-funksjonen np.outer kan være nyttig i utregning av punkt 4 ovenfor

Eksempel:
 La x,y være

x= [1 2 3] 
y= [ 1  0 -1]

Da blir np.outer(x,y)=
 [[ 1  0 -1]
 [ 2  0 -2]
 [ 3  0 -3]]


Numpyfunksjonen argmax kan være nyttig når man søker pivot-element (rad som skal byttes)

Skriv for eksempel: pivot = np.argmax(abs(A[P[k:], k])+k
 som gir pivot= 3 når k= 2


 AA=
 [[0.80454292 0.60114945 0.71518496 0.12215193 0.7560537 ]
 [0.52135159 0.75244512 0.37106933 0.85118679 0.07436968]
 [0.53884088 0.74475311 0.01385404 0.11787609 0.92569065]
 [0.92110619 0.32255828 0.40402752 0.15552985 0.95949371]
 [0.37801938 0.410

## Koder for forover- og bakover substitusjon
For å gjøre livet enklere angir vi her to rutiner som kan kalles for å løse Ax=b etter at man har LU-faktorisert med pivotering. Forutsetter at en matrise LU (overskrevet versjon av A) er beregnet, samt en permutasjonsvektor P

In [ ]:
def forward_subs(LU,P,b):
    ''' Forover substitusjonsalgoritme
    Input:
        LU inneholder både L og U, selv om kun L trengs i denne rutinen
        P Permutasjonsvektor av heltall
        b Vektor med høyresiden i problemet som skal løses
    Output:
        c Løsningen av det lineære nedretriangulære systemet Lc=Pb
    '''
    n, m = LU.shape
    Pb = b[P]
    c = np.zeros(n)
    c[0] = Pb[0]
    for k in range(1,n):
        c[k] = Pb[k] - LU[P[k],0:k] @ c[0:k]
        
    return c

def backward_subs(LU,P,c):
    ''' Bakover substitusjonsalgoritme
    Input:
        LU inneholder både L og U, selv om kun U trengs i denne rutinen
        P Permutasjonsvektor av heltall
        c Vektor med høyreside, dvs rutinen løser Ux=c
    Output:
        x Løsningen av det lineære øvretriangulre problemet Ux = c
    '''
    n,m = LU.shape
    x = np.zeros(n)
    x[n-1] = c[n-1]/LU[P[n-1],n-1]
    for k in range(n-1,0,-1):
        x[k-1] = (c[k-1]-LU[P[k-1],k:] @ x[k:])/LU[P[k-1],k-1]
        
    return x

## Funksjon for å lage A og b i Oppgave 2

In [132]:
def getAb():
    A=np.array([[0.3050, 0.5399, 0.9831, 0.4039, 0.1962],
                [0.2563, -0.1986, 0.7903, 0.6807, 0.5544],
                [0.7746, 0.6253, -0.1458, 0.1704,  0.5167],
                [0.4406, 0.9256, 0.4361, -0.2254, 0.7784],
                [0.4568, 0.2108, 0.6006, 0.3677, -0.8922]])
    b=np.array([0.9876,-1.231,0.0987,-0.5544,0.7712])
    return A,b
    
